export interface Spell {
  name: string;
  level: number; // 0 = cantrip, 1-9 = spell level
  school: string;
  castingTime: string;
  range: string;
  duration: string;
  components: string;
  description: string;
  classes: string[];
}

export const SPELLS: Spell[] = [
  // Cantrips
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    castingTime: "1 action",
    range: "30 feet",
    duration: "1 minute",
    components: "V, S",
    description: "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item, or pour the contents of a vial.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    castingTime: "1 action",
    range: "10 feet",
    duration: "Up to 1 hour",
    components: "V, S",
    description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of several minor magical effects: a sensory effect, light or snuff a flame, clean or soil an object, chill or warm material, make a mark, or create a trinket.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level.",
    classes: ["Warlock"],
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.",
    classes: ["Cleric"],
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 minute",
    components: "V, S",
    description: "You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.",
    classes: ["Cleric", "Druid"],
  },
  {
    name: "Toll the Dead",
    level: 0,
    school: "Necromancy",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.",
    classes: ["Cleric", "Warlock", "Wizard"],
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V",
    description: "You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you, it must succeed on a Wisdom saving throw or take 1d4 psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.",
    classes: ["Bard"],
  },
  {
    name: "Blade Ward",
    level: 0,
    school: "Abjuration",
    castingTime: "1 action",
    range: "Self",
    duration: "1 round",
    components: "V, S",
    description: "You extend your hand and trace a sigil of warding in the air. Until the end of your next turn, you have resistance against bludgeoning, piercing, and slashing damage dealt by weapon attacks.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    castingTime: "1 action",
    range: "30 feet",
    duration: "1 minute",
    components: "S, M",
    description: "You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again. If you create a sound, its volume can range from a whisper to a scream.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "Conjuration",
    castingTime: "1 action",
    range: "10 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "You extend your hand toward a creature you can see within range and project a puff of noxious gas. The creature must succeed on a Constitution saving throw or take 1d12 poison damage.",
    classes: ["Druid", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Shillelagh",
    level: 0,
    school: "Transmutation",
    castingTime: "1 bonus action",
    range: "Touch",
    duration: "1 minute",
    components: "V, S, M",
    description: "The wood of a club or quarterstaff you are holding is imbued with nature's power. For the duration, you can use your spellcasting ability instead of Strength for the attack and damage rolls of melee attacks using that weapon, and the weapon's damage die becomes a d8.",
    classes: ["Druid"],
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Up to 1 minute",
    components: "V",
    description: "You manifest a minor wonder, a sign of supernatural power, within range. You create one of several effects: your voice booms, flames flicker, tremors shake the ground, a door flies open or slams shut, your eyes turn jet black, or a harmless tremor shakes the ground.",
    classes: ["Cleric"],
  },
  {
    name: "True Strike",
    level: 0,
    school: "Divination",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Concentration, up to 1 round",
    components: "S",
    description: "You extend your hand and point a finger at a target in range. Your magic grants you a brief insight into the target's defenses. On your next turn, you gain advantage on your first attack roll against the target, provided that this spell hasn't ended.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    duration: "1 hour",
    components: "V, M",
    description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet. The light can be colored as you like. Completely covering the object with something opaque blocks the light.",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
  },

  // Level 1
  {
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "Self",
    duration: "1 round",
    components: "V, S",
    description: "An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (15-foot cone)",
    duration: "Instantaneous",
    components: "V, S",
    description: "As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. On a failed save, the creature takes 3d6 fire damage, or half as much on a successful save.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    components: "V, S",
    description: "A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "Divination",
    castingTime: "1 action",
    range: "Self",
    duration: "Concentration, up to 10 minutes",
    components: "V, S",
    description: "For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"],
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (15-foot cube)",
    duration: "Instantaneous",
    components: "V, S",
    description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw. On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn't pushed.",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
  },
  {
    name: "Charm Person",
    level: 1,
    school: "Enchantment",
    castingTime: "1 action",
    range: "30 feet",
    duration: "1 hour",
    components: "V, S",
    description: "You attempt to charm a humanoid you can see within range. It must make a Wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it.",
    classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "You bless up to three creatures of your choice within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.",
    classes: ["Cleric", "Paladin"],
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Evocation",
    castingTime: "1 bonus action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V",
    description: "A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    classes: ["Bard", "Cleric", "Druid"],
  },
  {
    name: "Grease",
    level: 1,
    school: "Conjuration",
    castingTime: "1 action",
    range: "60 feet",
    duration: "1 minute",
    components: "V, S, M",
    description: "Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into difficult terrain for the duration. When the grease appears, each creature standing in its area must succeed on a Dexterity saving throw or fall prone.",
    classes: ["Wizard"],
  },
  {
    name: "Identify",
    level: 1,
    school: "Divination",
    castingTime: "1 minute",
    range: "Touch",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "You choose one object that you must touch throughout the casting of the spell. If it is a magic item or some other magic-imbued object, you learn its properties and how to use them, whether it requires attunement to use, and how many charges it has, if any.",
    classes: ["Bard", "Wizard"],
  },
  {
    name: "Sleep",
    level: 1,
    school: "Enchantment",
    castingTime: "1 action",
    range: "90 feet",
    duration: "1 minute",
    components: "V, S, M",
    description: "This spell sends creatures into a magical slumber. Roll 5d8; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points.",
    classes: ["Bard", "Sorcerer", "Wizard"],
  },
  {
    name: "Witch Bolt",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "A beam of crackling, blue energy lances out toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against that creature. On a hit, the target takes 1d12 lightning damage, and on each of your turns for the duration, you can use your action to deal 1d12 lightning damage to the target automatically.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Hex",
    level: 1,
    school: "Enchantment",
    castingTime: "1 bonus action",
    range: "90 feet",
    duration: "Concentration, up to 1 hour",
    components: "V, S, M",
    description: "You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 necrotic damage to the target whenever you hit it with an attack. Also, choose one ability when you cast the spell. The target has disadvantage on ability checks made with the chosen ability.",
    classes: ["Warlock"],
  },
  {
    name: "Guiding Bolt",
    level: 1,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "1 round",
    components: "V, S",
    description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.",
    classes: ["Cleric"],
  },
  {
    name: "Command",
    level: 1,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    duration: "1 round",
    components: "V",
    description: "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. The spell has no effect if the target is undead, if it doesn't understand your language, or if your command is directly harmful to it.",
    classes: ["Cleric", "Paladin"],
  },

  // Level 2
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    castingTime: "1 bonus action",
    range: "Self",
    duration: "Instantaneous",
    components: "V",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.",
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 hour",
    components: "V, S, M",
    description: "A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. The spell ends for a target that attacks or casts a spell.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Shatter",
    level: 2,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw. A creature takes 3d8 thunder damage on a failed save, or half as much on a successful one.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Blindness/Deafness",
    level: 2,
    school: "Necromancy",
    castingTime: "1 action",
    range: "30 feet",
    duration: "1 minute",
    components: "V",
    description: "You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution saving throw. On a success, the spell ends.",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
  },
  {
    name: "Crown of Madness",
    level: 2,
    school: "Enchantment",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S",
    description: "One humanoid of your choice that you can see within range must succeed on a Wisdom saving throw or become charmed by you for the duration. While the target is charmed in this way, a twisted crown of jagged iron appears on its head, and a madness glows in its eyes.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Darkness",
    level: 2,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 10 minutes",
    components: "V, M",
    description: "Magical darkness spreads from a point you choose within range to fill a 15-foot-radius sphere for the duration. The darkness spreads around corners. A creature with darkvision can't see through this magical darkness, and nonmagical light can't illuminate it.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Flaming Sphere",
    level: 2,
    school: "Conjuration",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "A 5-foot-diameter sphere of fire appears in an unoccupied space of your choice within range and lasts for the duration. Any creature that ends its turn within 5 feet of the sphere must make a Dexterity saving throw. The creature takes 2d6 fire damage on a failed save, or half as much on a successful one.",
    classes: ["Druid", "Wizard"],
  },
  {
    name: "Knock",
    level: 2,
    school: "Transmutation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V",
    description: "Choose an object that you can see within range. The object can be a door, a box, a chest, a set of manacles, a padlock, or another object that contains a mundane or magical means that prevents access. A target that is held shut by a mundane lock or that is stuck or barred becomes unlocked, unstuck, or unbarred.",
    classes: ["Wizard"],
  },
  {
    name: "Mirror Image",
    level: 2,
    school: "Illusion",
    castingTime: "1 action",
    range: "Self",
    duration: "1 minute",
    components: "V, S",
    description: "Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it's impossible to track which image is real. You can use your action to dismiss the illusory duplicates.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Silence",
    level: 2,
    school: "Illusion",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 10 minutes",
    components: "V, S",
    description: "For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range. Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it.",
    classes: ["Bard", "Cleric", "Ranger"],
  },

  // Level 3
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "150 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much on a successful one.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (100-foot line)",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose. Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much on a successful one.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    castingTime: "1 reaction",
    range: "60 feet",
    duration: "Instantaneous",
    components: "S",
    description: "You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a success, the creature's spell fails and has no effect.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Fly",
    level: 3,
    school: "Transmutation",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 10 minutes",
    components: "V, S, M",
    description: "You touch a willing creature. The target gains a flying speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft, unless it can stop the fall.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Haste",
    level: 3,
    school: "Transmutation",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Slow",
    level: 3,
    school: "Transmutation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "You alter time around up to six creatures of your choice in a 40-foot cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration. An affected target's speed is halved, it takes a −2 penalty to AC and Dexterity saving throws, and it can't use reactions.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Animate Dead",
    level: 3,
    school: "Necromancy",
    castingTime: "1 minute",
    range: "10 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range. Your spell imbues the target with a foul mimicry of life, raising it as an undead creature. The target becomes a skeleton if you chose bones or a zombie if you chose a corpse.",
    classes: ["Cleric", "Wizard"],
  },
  {
    name: "Hypnotic Pattern",
    level: 3,
    school: "Illusion",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 1 minute",
    components: "S, M",
    description: "You create a twisting pattern of colors that weaves through the air inside a 30-foot cube within range. The pattern appears for a moment and vanishes. Each creature in the area who sees the pattern must make a Wisdom saving throw. On a failed save, the creature becomes charmed for the duration.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Call Lightning",
    level: 3,
    school: "Conjuration",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 10 minutes",
    components: "V, S",
    description: "A storm cloud appears in the shape of a cylinder that is 10 feet tall with a 60-foot radius, centered on a point you can see above you. When you cast the spell, choose a point you can see under the cloud. A bolt of lightning flashes down from the cloud to that point. Each creature within 5 feet of that point must make a Dexterity saving throw, taking 3d10 lightning damage on a failed save.",
    classes: ["Druid"],
  },
  {
    name: "Spirit Guardians",
    level: 3,
    school: "Conjuration",
    castingTime: "1 action",
    range: "Self (15-foot radius)",
    duration: "Concentration, up to 10 minutes",
    components: "V, S, M",
    description: "You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. If you are good or neutral, their spectral form appears angelic or fey. If you are evil, they appear fiendish. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it.",
    classes: ["Cleric"],
  },

  // Level 4
  {
    name: "Polymorph",
    level: 4,
    school: "Transmutation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 1 hour",
    components: "V, S, M",
    description: "This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The transformation lasts for the duration, or until the target drops to 0 hit points or dies.",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
  },
  {
    name: "Banishment",
    level: 4,
    school: "Abjuration",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished. If the target is native to a different plane of existence than the one you're on, the target is banished with a faint popping noise, returning to its home plane.",
    classes: ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Greater Invisibility",
    level: 4,
    school: "Illusion",
    castingTime: "1 action",
    range: "Touch",
    duration: "Concentration, up to 1 minute",
    components: "V, S",
    description: "You or a creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person. Unlike Invisibility, this spell does not end when the target attacks or casts a spell.",
    classes: ["Bard", "Sorcerer", "Wizard"],
  },
  {
    name: "Wall of Fire",
    level: 4,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "You create a wall of fire on a solid surface within range. The wall can be up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick. The wall is opaque and lasts for the duration. When the wall appears, each creature within its area must make a Dexterity saving throw.",
    classes: ["Druid", "Sorcerer", "Wizard"],
  },
  {
    name: "Blight",
    level: 4,
    school: "Necromancy",
    castingTime: "1 action",
    range: "30 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "Necromantic energy washes over a creature of your choice that you can see within range, draining moisture and vitality from it. The target must make a Constitution saving throw. The target takes 8d8 necrotic damage on a failed save, or half as much on a successful one.",
    classes: ["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Confusion",
    level: 4,
    school: "Enchantment",
    castingTime: "1 action",
    range: "90 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "This spell assaults and twists creatures' minds, spawning delusions and provoking uncontrolled actions. Each creature in a 10-foot-radius sphere centered on a point you choose within range must succeed on a Wisdom saving throw when you cast this spell or become affected by it.",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
  },

  // Level 5
  {
    name: "Cone of Cold",
    level: 5,
    school: "Evocation",
    castingTime: "1 action",
    range: "Self (60-foot cone)",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much on a successful one. A creature killed by this spell becomes a frozen statue until it thaws.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Hold Monster",
    level: 5,
    school: "Enchantment",
    castingTime: "1 action",
    range: "90 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S, M",
    description: "Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration. This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Mass Cure Wounds",
    level: 5,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point. Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.",
    classes: ["Bard", "Cleric", "Druid"],
  },
  {
    name: "Wall of Force",
    level: 5,
    school: "Evocation",
    castingTime: "1 action",
    range: "120 feet",
    duration: "Concentration, up to 10 minutes",
    components: "V, S, M",
    description: "An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. The wall is immune to all damage and can't be dispelled by dispel magic.",
    classes: ["Wizard"],
  },
  {
    name: "Dominate Person",
    level: 5,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Concentration, up to 1 minute",
    components: "V, S",
    description: "You attempt to beguile a humanoid that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration. While the target is charmed, you have a telepathic link with it as long as the two of you are on the same plane of existence.",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
  },
  {
    name: "Flame Strike",
    level: 5,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A vertical column of divine fire roars down from the heavens in a location you specify. Each creature in a 10-foot-radius, 40-foot-high cylinder centered on a point within range must make a Dexterity saving throw. A creature takes 4d6 fire damage and 4d6 radiant damage on a failed save, or half as much on a successful one.",
    classes: ["Cleric"],
  },

  // Level 6+
  {
    name: "Chain Lightning",
    level: 6,
    school: "Evocation",
    castingTime: "1 action",
    range: "150 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target. A target can be a creature or an object and can be targeted by only one of the bolts.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Disintegrate",
    level: 6,
    school: "Transmutation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "A thin green ray springs from your pointing finger to a target you can see within range. The target can be a creature, an object, or a creation of magical force. A creature targeted by this spell must make a Dexterity saving throw. On a failed save, the target takes 10d6 + 40 force damage.",
    classes: ["Sorcerer", "Wizard"],
  },
  {
    name: "Heal",
    level: 6,
    school: "Evocation",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V, S",
    description: "Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.",
    classes: ["Cleric", "Druid"],
  },
  {
    name: "Plane Shift",
    level: 7,
    school: "Conjuration",
    castingTime: "1 action",
    range: "Touch",
    duration: "Instantaneous",
    components: "V, S, M",
    description: "You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence. You can specify a target destination in general terms, such as the City of Brass on the Elemental Plane of Fire or the palace of Dispater on the second level of the Nine Hells.",
    classes: ["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
  },
  {
    name: "Power Word Kill",
    level: 9,
    school: "Enchantment",
    castingTime: "1 action",
    range: "60 feet",
    duration: "Instantaneous",
    components: "V",
    description: "You utter a word of power that can compel one creature you can see within range to die instantly. If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.",
    classes: ["Sorcerer", "Warlock", "Wizard"],
  },
];
