// ---------------------------------------------------------------------------
// Static spell-to-class mapping for D&D 5e (PHB, XGE, TCE)
// Keys are lowercase spell names; values are arrays of class names.
// ---------------------------------------------------------------------------

export const SPELL_CLASSES = [
  "Artificer",
  "Bard",
  "Cleric",
  "Druid",
  "Paladin",
  "Ranger",
  "Sorcerer",
  "Warlock",
  "Wizard",
] as const;

export type SpellClass = (typeof SPELL_CLASSES)[number];

/** Maps spell name (lowercase) → array of class names that can use it */
export const SPELL_CLASS_MAP: Record<string, SpellClass[]> = {
  // A
  "absorb elements": ["Artificer", "Druid", "Ranger", "Wizard"],
  "acid splash": ["Sorcerer", "Wizard"],
  "aid": ["Artificer", "Cleric", "Paladin", "Ranger"],
  "alarm": ["Artificer", "Ranger", "Wizard"],
  "alter self": ["Sorcerer", "Wizard"],
  "animal friendship": ["Bard", "Druid", "Ranger"],
  "animal messenger": ["Bard", "Druid", "Ranger"],
  "animal shapes": ["Druid"],
  "animate dead": ["Cleric", "Wizard"],
  "animate objects": ["Bard", "Sorcerer", "Wizard"],
  "antilife shell": ["Druid"],
  "antimagic field": ["Cleric", "Wizard"],
  "antipathy/sympathy": ["Druid", "Wizard"],
  "arcane eye": ["Artificer", "Wizard"],
  "arcane gate": ["Sorcerer", "Warlock", "Wizard"],
  "arcane lock": ["Artificer", "Wizard"],
  "armor of agathys": ["Warlock"],
  "arms of hadar": ["Warlock"],
  "astral projection": ["Cleric", "Warlock", "Wizard"],
  "augury": ["Cleric", "Druid"],
  "aura of life": ["Paladin"],
  "aura of purity": ["Paladin"],
  "aura of vitality": ["Paladin"],
  "awaken": ["Bard", "Druid"],
  // B
  "bane": ["Bard", "Cleric"],
  "banishment": ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"],
  "banishing smite": ["Paladin"],
  "barkskin": ["Druid", "Ranger"],
  "beacon of hope": ["Cleric"],
  "beast bond": ["Druid", "Ranger"],
  "beast sense": ["Druid", "Ranger"],
  "bestow curse": ["Bard", "Cleric", "Wizard"],
  "bigby's hand": ["Wizard"],
  "blade ward": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "bless": ["Cleric", "Paladin"],
  "blight": ["Druid", "Sorcerer", "Warlock", "Wizard"],
  "blindness/deafness": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
  "blink": ["Sorcerer", "Wizard"],
  "blur": ["Artificer", "Sorcerer", "Wizard"],
  "branding smite": ["Paladin"],
  "burning hands": ["Sorcerer", "Wizard"],
  // C
  "call lightning": ["Druid"],
  "calm emotions": ["Bard", "Cleric"],
  "catnap": ["Bard", "Sorcerer", "Wizard"],
  "chain lightning": ["Sorcerer", "Wizard"],
  "charm monster": ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
  "charm person": ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
  "chromatic orb": ["Sorcerer", "Wizard"],
  "circle of death": ["Sorcerer", "Warlock", "Wizard"],
  "clairvoyance": ["Bard", "Cleric", "Sorcerer", "Wizard"],
  "clone": ["Wizard"],
  "cloud of daggers": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "cloudkill": ["Sorcerer", "Wizard"],
  "color spray": ["Sorcerer", "Wizard"],
  "command": ["Cleric", "Paladin"],
  "commune": ["Cleric"],
  "commune with nature": ["Druid", "Ranger"],
  "compelled duel": ["Paladin"],
  "comprehend languages": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "cone of cold": ["Sorcerer", "Wizard"],
  "confusion": ["Bard", "Druid", "Sorcerer", "Wizard"],
  "conjure animals": ["Druid", "Ranger"],
  "conjure barrage": ["Ranger"],
  "conjure celestial": ["Cleric"],
  "conjure elemental": ["Druid", "Wizard"],
  "conjure fey": ["Druid", "Warlock"],
  "conjure minor elementals": ["Druid", "Wizard"],
  "conjure volley": ["Ranger"],
  "conjure woodland beings": ["Druid", "Ranger"],
  "contact other plane": ["Warlock", "Wizard"],
  "contingency": ["Wizard"],
  "continual flame": ["Artificer", "Cleric", "Wizard"],
  "control water": ["Cleric", "Druid", "Wizard"],
  "control weather": ["Cleric", "Druid", "Wizard"],
  "cordon of arrows": ["Ranger"],
  "counterspell": ["Sorcerer", "Warlock", "Wizard"],
  "create food and water": ["Cleric", "Paladin"],
  "create or destroy water": ["Cleric", "Druid"],
  "create undead": ["Cleric", "Warlock", "Wizard"],
  "crown of madness": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "cure wounds": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Ranger"],
  // D
  "dancing lights": ["Artificer", "Bard", "Sorcerer", "Wizard"],
  "darkness": ["Sorcerer", "Warlock", "Wizard"],
  "darkvision": ["Artificer", "Druid", "Ranger", "Sorcerer", "Wizard"],
  "daylight": ["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"],
  "death ward": ["Artificer", "Cleric", "Paladin"],
  "demiplane": ["Warlock", "Wizard"],
  "destructive wave": ["Paladin"],
  "detect evil and good": ["Cleric", "Paladin"],
  "detect magic": [
    "Artificer",
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
    "Sorcerer",
    "Warlock",
    "Wizard",
  ],
  "detect poison and disease": ["Cleric", "Druid", "Paladin", "Ranger"],
  "detect thoughts": ["Bard", "Sorcerer", "Wizard"],
  "dimension door": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "disguise self": ["Bard", "Sorcerer", "Wizard"],
  "disintegrate": ["Sorcerer", "Wizard"],
  "dispel evil and good": ["Cleric", "Paladin"],
  "dispel magic": ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
  "dissonant whispers": ["Bard"],
  "divination": ["Cleric", "Druid", "Wizard"],
  "divine favor": ["Paladin"],
  "divine word": ["Cleric"],
  "dominate beast": ["Druid", "Sorcerer"],
  "dominate monster": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "dominate person": ["Bard", "Sorcerer", "Wizard"],
  "dream": ["Bard", "Warlock", "Wizard"],
  "druidcraft": ["Druid"],
  // E
  "earthquake": ["Cleric", "Druid", "Sorcerer"],
  "eldritch blast": ["Warlock"],
  "elemental weapon": ["Artificer", "Paladin"],
  "enhance ability": ["Artificer", "Bard", "Cleric", "Druid", "Sorcerer"],
  "enlarge/reduce": ["Artificer", "Sorcerer", "Wizard"],
  "ensnaring strike": ["Ranger"],
  "entangle": ["Druid"],
  "enthrall": ["Bard", "Warlock"],
  "erupting earth": ["Druid", "Sorcerer", "Wizard"],
  "etherealness": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
  "evard's black tentacles": ["Wizard"],
  "expeditious retreat": ["Artificer", "Sorcerer", "Warlock", "Wizard"],
  "eyebite": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  // F
  "fabricate": ["Artificer", "Wizard"],
  "faerie fire": ["Artificer", "Bard", "Druid"],
  "false life": ["Artificer", "Sorcerer", "Wizard"],
  "far step": ["Sorcerer", "Warlock", "Wizard"],
  "fear": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "feather fall": ["Artificer", "Bard", "Sorcerer", "Wizard"],
  "feeblemind": ["Bard", "Druid", "Warlock", "Wizard"],
  "find familiar": ["Wizard"],
  "find greater steed": ["Paladin"],
  "find steed": ["Paladin"],
  "find traps": ["Cleric", "Druid", "Ranger"],
  "finger of death": ["Sorcerer", "Warlock", "Wizard"],
  "fire bolt": ["Sorcerer", "Wizard"],
  "fire shield": ["Sorcerer", "Wizard"],
  "fire storm": ["Cleric", "Druid", "Sorcerer"],
  "fireball": ["Sorcerer", "Wizard"],
  "flame blade": ["Druid"],
  "flame strike": ["Cleric"],
  "flaming sphere": ["Druid", "Wizard"],
  "fly": ["Artificer", "Sorcerer", "Warlock", "Wizard"],
  "fog cloud": ["Druid", "Ranger", "Sorcerer", "Warlock", "Wizard"],
  "forbiddance": ["Cleric"],
  "forcecage": ["Bard", "Warlock", "Wizard"],
  "foresight": ["Bard", "Druid", "Warlock", "Wizard"],
  "freedom of movement": [
    "Artificer",
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
  ],
  // G
  "gaseous form": ["Sorcerer", "Warlock", "Wizard"],
  "geas": ["Bard", "Cleric", "Druid", "Paladin", "Wizard"],
  "gentle repose": ["Cleric", "Wizard"],
  "giant insect": ["Druid"],
  "globe of invulnerability": ["Sorcerer", "Wizard"],
  "glyph of warding": ["Artificer", "Bard", "Cleric", "Wizard"],
  "grease": ["Artificer", "Wizard"],
  "grasping vine": ["Druid", "Ranger"],
  "greater invisibility": ["Bard", "Sorcerer", "Wizard"],
  "greater restoration": ["Artificer", "Bard", "Cleric", "Druid", "Paladin"],
  "guardian of nature": ["Druid", "Ranger"],
  "guards and wards": ["Bard", "Wizard"],
  "guidance": ["Cleric", "Druid"],
  "guiding bolt": ["Cleric"],
  "gust": ["Druid", "Sorcerer", "Wizard"],
  // H
  "hail of thorns": ["Ranger"],
  "hallucinatory terrain": ["Bard", "Druid", "Warlock", "Wizard"],
  "harm": ["Cleric"],
  "haste": ["Artificer", "Sorcerer", "Wizard"],
  "heal": ["Cleric", "Druid"],
  "healing word": ["Bard", "Cleric", "Druid"],
  "heat metal": ["Artificer", "Bard", "Druid"],
  "hellish rebuke": ["Warlock"],
  "heroes' feast": ["Cleric", "Druid"],
  "heroism": ["Bard", "Paladin"],
  "hex": ["Warlock"],
  "hold monster": [
    "Bard",
    "Sorcerer",
    "Warlock",
    "Wizard",
  ],
  "hold person": ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
  "holy aura": ["Cleric", "Paladin"],
  "hunger of hadar": ["Warlock"],
  "hunter's mark": ["Ranger"],
  "hypnotic pattern": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  // I
  "ice storm": ["Druid", "Sorcerer", "Wizard"],
  "identify": ["Artificer", "Bard", "Wizard"],
  "illusory script": ["Bard", "Warlock", "Wizard"],
  "imprisonment": ["Warlock", "Wizard"],
  "inflict wounds": ["Cleric"],
  "insect plague": ["Cleric", "Druid", "Sorcerer"],
  "invisibility": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
  // J
  "jump": [
    "Artificer",
    "Bard",
    "Druid",
    "Ranger",
    "Sorcerer",
    "Wizard",
  ],
  // K
  "knock": ["Bard", "Sorcerer", "Wizard"],
  // L
  "legend lore": ["Bard", "Cleric", "Wizard"],
  "leomund's secret chest": ["Wizard"],
  "leomund's tiny hut": ["Bard", "Wizard"],
  "lesser restoration": ["Artificer", "Bard", "Cleric", "Druid", "Paladin", "Ranger"],
  "levitate": ["Artificer", "Sorcerer", "Wizard"],
  "light": ["Artificer", "Bard", "Cleric", "Sorcerer", "Wizard"],
  "lightning arrow": ["Ranger"],
  "lightning bolt": ["Sorcerer", "Wizard"],
  "locate animals or plants": ["Bard", "Druid", "Ranger"],
  "locate creature": ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"],
  "locate object": [
    "Bard",
    "Cleric",
    "Druid",
    "Paladin",
    "Ranger",
    "Wizard",
  ],
  "longstrider": ["Artificer", "Bard", "Druid", "Ranger", "Wizard"],
  // M
  "maelstrom": ["Druid"],
  "mage armor": ["Sorcerer", "Wizard"],
  "mage hand": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
  "magic circle": ["Cleric", "Paladin", "Warlock", "Wizard"],
  "magic jar": ["Wizard"],
  "magic missile": ["Sorcerer", "Wizard"],
  "magic mouth": ["Bard", "Wizard"],
  "magic weapon": ["Artificer", "Paladin", "Wizard"],
  "major image": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "mass cure wounds": ["Bard", "Cleric", "Druid"],
  "mass heal": ["Cleric"],
  "mass healing word": ["Bard", "Cleric"],
  "mass suggestion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "maximilian's earthen grasp": ["Sorcerer", "Wizard"],
  "maze": ["Wizard"],
  "meld into stone": ["Cleric", "Druid"],
  "melf's acid arrow": ["Wizard"],
  "melf's minute meteors": ["Sorcerer", "Wizard"],
  "mending": ["Artificer", "Bard", "Cleric", "Druid", "Sorcerer", "Wizard"],
  "mental prison": ["Sorcerer", "Warlock", "Wizard"],
  "message": ["Artificer", "Bard", "Sorcerer", "Wizard"],
  "mind blank": ["Bard", "Wizard"],
  "minor illusion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "mirage arcane": ["Bard", "Druid", "Wizard"],
  "mirror image": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
  "mislead": ["Bard", "Sorcerer", "Wizard"],
  "misty step": ["Sorcerer", "Warlock", "Wizard"],
  "modify memory": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "moonbeam": ["Druid"],
  "mordenkainen's faithful hound": ["Artificer", "Wizard"],
  "mordenkainen's magnificent mansion": ["Bard", "Wizard"],
  "mordenkainen's private sanctum": ["Wizard"],
  "mordenkainen's sword": ["Bard", "Wizard"],
  "move earth": ["Druid", "Sorcerer", "Wizard"],
  // N
  "nathair's mischief": ["Bard", "Sorcerer", "Wizard"],
  "nondetection": ["Bard", "Ranger", "Wizard"],
  "nystul's magic aura": ["Wizard"],
  // O
  "otiluke's freezing sphere": ["Wizard"],
  "otiluke's resilient sphere": ["Artificer", "Wizard"],
  "otto's irresistible dance": ["Bard", "Wizard"],
  // P
  "pass without trace": ["Druid", "Ranger"],
  "passwall": ["Wizard"],
  "phantasmal force": ["Bard", "Wizard"],
  "phantasmal killer": ["Wizard"],
  "phantom steed": ["Wizard"],
  "plane shift": ["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
  "plant growth": ["Bard", "Druid", "Ranger"],
  "poison spray": ["Druid", "Sorcerer", "Warlock", "Wizard"],
  "polymorph": ["Bard", "Druid", "Sorcerer", "Wizard"],
  "power word heal": ["Bard", "Cleric"],
  "power word kill": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "power word pain": ["Sorcerer", "Warlock", "Wizard"],
  "power word stun": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "prayer of healing": ["Cleric"],
  "prestidigitation": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "prismatic spray": ["Sorcerer", "Wizard"],
  "prismatic wall": ["Sorcerer", "Wizard"],
  "produce flame": ["Druid"],
  "programmed illusion": ["Bard", "Wizard"],
  "project image": ["Bard", "Wizard"],
  "protection from energy": ["Artificer", "Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"],
  "protection from evil and good": ["Cleric", "Paladin", "Warlock", "Wizard"],
  "protection from poison": ["Artificer", "Cleric", "Druid", "Paladin", "Ranger"],
  "psychic scream": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "purify food and drink": ["Artificer", "Cleric", "Druid", "Paladin"],
  "pyrotechnics": ["Artificer", "Bard", "Sorcerer", "Wizard"],
  // R
  "raise dead": ["Bard", "Cleric", "Paladin"],
  "ray of enfeeblement": ["Warlock", "Wizard"],
  "ray of frost": ["Sorcerer", "Wizard"],
  "ray of sickness": ["Sorcerer", "Warlock", "Wizard"],
  "remove curse": ["Cleric", "Paladin", "Warlock", "Wizard"],
  "resistance": ["Artificer", "Cleric", "Druid"],
  "revivify": ["Artificer", "Cleric", "Druid", "Paladin"],
  "rope trick": ["Artificer", "Wizard"],
  // S
  "sacred flame": ["Cleric"],
  "sanctuary": ["Artificer", "Cleric", "Paladin"],
  "scatter": ["Sorcerer", "Warlock", "Wizard"],
  "scrying": ["Bard", "Cleric", "Druid", "Warlock", "Wizard"],
  "see invisibility": ["Artificer", "Bard", "Sorcerer", "Warlock", "Wizard"],
  "seeming": ["Bard", "Sorcerer", "Wizard"],
  "sending": ["Bard", "Cleric", "Warlock", "Wizard"],
  "shadow of moil": ["Warlock"],
  "shape water": ["Druid", "Sorcerer", "Wizard"],
  "shapechange": ["Druid", "Wizard"],
  "shatter": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "shield": ["Artificer", "Sorcerer", "Wizard"],
  "shield of faith": ["Cleric", "Paladin"],
  "shillelagh": ["Druid"],
  "shocking grasp": ["Artificer", "Sorcerer", "Wizard"],
  "silence": ["Bard", "Cleric", "Ranger"],
  "silent image": ["Bard", "Sorcerer", "Wizard"],
  "simulacrum": ["Wizard"],
  "sleep": ["Bard", "Sorcerer", "Wizard"],
  "slow": ["Sorcerer", "Wizard"],
  "spare the dying": ["Cleric"],
  "speak with animals": ["Bard", "Druid", "Ranger"],
  "speak with dead": ["Bard", "Cleric"],
  "speak with plants": ["Bard", "Druid", "Ranger"],
  "spider climb": ["Artificer", "Sorcerer", "Warlock", "Wizard"],
  "spike growth": ["Druid", "Ranger"],
  "spirit guardians": ["Cleric"],
  "spiritual weapon": ["Cleric"],
  "staggering smite": ["Paladin"],
  "steel wind strike": ["Ranger", "Wizard"],
  "stone shape": ["Artificer", "Cleric", "Druid", "Wizard"],
  "stoneskin": ["Artificer", "Druid", "Ranger", "Sorcerer", "Wizard"],
  "suggestion": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "summon fey": ["Druid", "Ranger", "Warlock", "Wizard"],
  "summon fiend": ["Warlock", "Wizard"],
  "summon shadowspawn": ["Ranger", "Warlock", "Wizard"],
  "summon undead": ["Warlock", "Wizard"],
  "sunbeam": ["Cleric", "Druid", "Sorcerer", "Wizard"],
  "sunburst": ["Cleric", "Druid", "Sorcerer", "Wizard"],
  "swift quiver": ["Ranger"],
  "symbol": ["Bard", "Cleric", "Wizard"],
  // T
  "tasha's caustic brew": ["Artificer", "Sorcerer", "Wizard"],
  "tasha's hideous laughter": ["Bard", "Wizard"],
  "tasha's mind whip": ["Sorcerer", "Wizard"],
  "telekinesis": ["Sorcerer", "Wizard"],
  "telepathy": ["Wizard"],
  "teleport": ["Bard", "Sorcerer", "Wizard"],
  "teleportation circle": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  "thaumaturgy": ["Cleric"],
  "thunderous smite": ["Paladin"],
  "thunderwave": ["Bard", "Druid", "Sorcerer", "Wizard"],
  "tidal wave": ["Druid", "Sorcerer", "Wizard"],
  "time stop": ["Sorcerer", "Wizard"],
  "tiny servant": ["Artificer", "Wizard"],
  "thorn whip": ["Druid"],
  "tongues": ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
  "transmute rock": ["Druid", "Wizard"],
  "tree stride": ["Druid", "Ranger"],
  "true polymorph": ["Bard", "Warlock", "Wizard"],
  "true resurrection": ["Cleric", "Druid"],
  "true seeing": ["Artificer", "Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
  "true strike": ["Bard", "Sorcerer", "Warlock", "Wizard"],
  // U
  "unseen servant": ["Bard", "Warlock", "Wizard"],
  // V
  "vampiric touch": ["Sorcerer", "Warlock", "Wizard"],
  "vicious mockery": ["Bard"],
  "vow of enmity": ["Paladin"],
  // W
  "wall of fire": ["Druid", "Sorcerer", "Wizard"],
  "wall of force": ["Wizard"],
  "wall of ice": ["Wizard"],
  "wall of stone": ["Artificer", "Druid", "Sorcerer", "Wizard"],
  "wall of thorns": ["Druid"],
  "warding wind": ["Druid", "Sorcerer", "Wizard"],
  "water breathing": ["Druid", "Ranger", "Sorcerer", "Wizard"],
  "water walk": ["Cleric", "Druid", "Ranger", "Sorcerer"],
  "web": ["Artificer", "Sorcerer", "Wizard"],
  "weird": ["Wizard"],
  "whirlwind": ["Druid", "Sorcerer", "Wizard"],
  "wind walk": ["Druid"],
  "wind wall": ["Druid", "Ranger"],
  "wish": ["Sorcerer", "Wizard"],
  "witch bolt": ["Sorcerer", "Warlock", "Wizard"],
  "word of radiance": ["Cleric"],
  "wrathful smite": ["Paladin"],
  // Z
  "zephyr strike": ["Ranger"],
  "zone of truth": ["Bard", "Cleric", "Paladin"],
};

/** Returns classes for a given spell name, or [] if unknown */
export function getSpellClasses(spellName: string): SpellClass[] {
  return SPELL_CLASS_MAP[spellName.toLowerCase()] ?? [];
}
